=== mariamiawad/VIS_Sample_Project/prj/data/CteSetup.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="CteSetup">
		<xs:annotation>
			<xs:documentation>Configuration of CTE</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="Variant" type="Variant">
					<xs:annotation>
						<xs:documentation>A variant is selected with exu type and the variant parameter to the CTE.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Include" type="Include">
					<xs:annotation>
						<xs:documentation>Include another file containing CteSetup configurations.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="ObjectPathFilter">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="MatchingRegex" type="xs:string"/>
							<xs:element name="ReplaceRegex" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:attribute name="Format" type="xs:int" use="required">
				<xs:annotation>
					<xs:documentation>Format version</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Variant">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Libraries">
				<xs:annotation>
					<xs:documentation>List of libraries to be loaded.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="Library">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="Type" use="required">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="ExuObject"/>
														<xs:enumeration value="ExuValueKey"/>
														<xs:enumeration value="ValueString"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
											<xs:attribute name="Name" use="required"/>
											<xs:attribute name="Value" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="ClassName" type="xs:string" use="required"/>
								<xs:attribute name="InstanceName" type="xs:string"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Tests">
				<xs:annotation>
					<xs:documentation>Tree structure of all tests to be loaded.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element name="Group" type="Group">
							<xs:annotation>
								<xs:documentation>Sub tree in the test structure</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="Test" type="Test">
							<xs:annotation>
								<xs:documentation>A runnable test</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:choice>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="ExuType" type="xs:string" use="required"/>
		<xs:attribute name="Variant" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Test">
		<xs:attribute name="ClassName" type="xs:string" use="required"/>
		<xs:attribute name="Name" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="Include">
		<xs:attribute name="File" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Group">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Test" type="Test"/>
			<xs:element name="Group" type="Group"/>
		</xs:choice>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="Preamble" type="xs:string" use="optional"/>
	</xs:complexType>
</xs:schema>

=== mariamiawad/VIS_Sample_Project/prj/data/CteSetup.xml
<?xml version="1.0" encoding="UTF-8"?>
<CteSetup 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="CteSetup.xsd" Format="2">
	
	<!-- see the schema file CteSetup.xsd for the allowed elements -->
	
	<!--
	<Variant ExuType="TS" Variant="MyVariant2">
	</Variant>
	
	<Variant ExuType="TS" Variant="MyVariant1">
		<Libraries>
			<Library ClassName="prj.demo.PwmLib" InstanceName="green" >
				<Parameter Type="ExuObject" Name="pwm" Value="dif0/objPWM_GREEN_STA"/>
			</Library>
			<Library ClassName="prj.demo.PwmLib" InstanceName="red" >
				<Parameter Type="ExuObject" Name="pwm" Value="dif0/objPWM_GREEN_STA"/>
			</Library>
			<Library ClassName="stdlib.pps.ToellnerPowerSupply" >
				<Parameter Type="ExuObject" Name="ToeDriver" Value="modMM/objGeneric/objToeDriver"/>
			</Library>
		</Libraries>
		<Tests>
			<Group Name="FunctionTest">
				<Test ClassName="prj.demo.DemoTest"/>
			</Group>
		</Tests>
	</Variant>
	-->

	<ObjectPathFilter>
		<MatchingRegex>^mod../obj_MCONTROL/msgGeneralMessage\(([^)]*)\)</MatchingRegex>
		<ReplaceRegex>$1</ReplaceRegex>
	</ObjectPathFilter>

	<!-- remove prefixes mod/obj/fnc/msg -->
	<ObjectPathFilter>
		<MatchingRegex>^mod(..)/</MatchingRegex>
		<!-- with empty replace, the module is completely removed, 
		     with '$1/' replace, the 2-letter name will stay -->
		<ReplaceRegex></ReplaceRegex>
	</ObjectPathFilter>
	<ObjectPathFilter>
		<MatchingRegex>(^|/)(obj|msg|fnc)</MatchingRegex>
		<ReplaceRegex>$1</ReplaceRegex>
	</ObjectPathFilter>
	<ObjectPathFilter>
		<MatchingRegex>(^|/)_MCONTROL</MatchingRegex>
		<ReplaceRegex>$1</ReplaceRegex>
	</ObjectPathFilter>
	<ObjectPathFilter>
		<MatchingRegex>^Exu (disconnected|connected) \(ID=/192.168.144.(\d+)\) (.*)</MatchingRegex>
		<ReplaceRegex>Module IP=$2 $3</ReplaceRegex>
	</ObjectPathFilter>

	<!-- GeneralMessage removal, the text of it is enough -->
	
	<ObjectPathFilter>
		<MatchingRegex>/WaitForEventTimeout\(.*</MatchingRegex>
		<ReplaceRegex>pauseUntilEvent Timeout</ReplaceRegex>
	</ObjectPathFilter>
	<ObjectPathFilter>
		<MatchingRegex>/WaitForEvent"(pauseUntilEvent\([^)]*\))".*</MatchingRegex>
		<ReplaceRegex>$1</ReplaceRegex>
	</ObjectPathFilter>
	<ObjectPathFilter>
		<MatchingRegex>^/(HilStarted|HilStartMarker|HilStart|HilEndMarker|HilEnd|HilFinished|TestStartMarker)\b.*</MatchingRegex>
		<ReplaceRegex>$1</ReplaceRegex>
	</ObjectPathFilter>
	<ObjectPathFilter>
		<MatchingRegex>/GeneralMessage\(([^)]*)\)</MatchingRegex>
		<ReplaceRegex> $1</ReplaceRegex>
	</ObjectPathFilter>
	
	<ObjectPathFilter>
		<MatchingRegex>^Cmt Level Enter (\d+):</MatchingRegex>
		<ReplaceRegex>&gt;&gt;&gt; $1</ReplaceRegex>
	</ObjectPathFilter>
	<ObjectPathFilter>
		<MatchingRegex>^Cmt Level Leave (\d+):</MatchingRegex>
		<ReplaceRegex>&lt;&lt;&lt; $1</ReplaceRegex>
	</ObjectPathFilter>
	
	<ObjectPathFilter>
		<MatchingRegex>^\[castle\..*\.QueueClosed\.\]\.msgQueueClosed</MatchingRegex>
		<ReplaceRegex>Queue/Report closed </ReplaceRegex>
	</ObjectPathFilter>
	<ObjectPathFilter>
		<MatchingRegex>^\[castle\..*\.QueueStarted\.\]\.msgQueueStarted</MatchingRegex>
		<ReplaceRegex>Queue/Report started </ReplaceRegex>
	</ObjectPathFilter>
	<ObjectPathFilter>
		<MatchingRegex>^\[.*\.\]\.msg([^ ]+)</MatchingRegex>
		<ReplaceRegex>$1</ReplaceRegex>
	</ObjectPathFilter>
	
	<!-- Enum value without the integer value and brackets -->
	<ObjectPathFilter>
		<MatchingRegex>(\(|, )\d+ «(\w+)»</MatchingRegex>
		<ReplaceRegex>$1$2</ReplaceRegex>
	</ObjectPathFilter>
	
</CteSetup>
